accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns =[
    path('signup/', views.signup_view, name = 'signup'),
    path('login/', views.login_view, name = 'login'),
    path('logout/', views.logout_view, name = 'logout'),

]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.article_list, name = "list"),
    path('create/', views.create_article, name = "create"),
    path('<slug:slug>/', views.article_details, name= "detail"),
]

djangonautic/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.urls import include 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('about/', views.about),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),


]

urlpatterns+= staticfiles_urlpatterns()

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length = 200)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'slug', 'body']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
# Create your views here.

def signup_view(request):

    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('articles:list')
    
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            return redirect('articles:list')

    
    else:
        form = AuthenticationForm()

    return render(request, 'accounts/login.html', {'form':form} )

def logout_view(request):
    #if request.method == 'POST':
    logout(request)
        
    return redirect('articles:list')

articles/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Article
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def article_list(request):
    articles = Article.objects.all()
    return render(request, 'articles/articles_list.html', {'articles': articles})

def article_details(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article.html', {'article': article} )


@login_required(login_url="/accounts/login/")
def create_article(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author= request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()

    return render(request, 'articles/create.html', {'form':form})

djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    #return HttpResponse('Homepage')
    return render(request, 'homepage.html')
def about(request):
    #return HttpResponse('about')
    return render(request, 'about.html')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Logiin</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{form}}
        {% if request.GET.next %}
            <input type="hidden" name='next' value ='{{request.GET.next}}'>
        {% endif %}
        <input type="submit" value="login">
    </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="/accounts/signup/" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="signup">
    </form>
{% endblock %}

articles/templates/articles/article.html
{% extends 'base_layout.html' %}
 {% block content %}
 <div class="article_detail">
    <h2>{{article.title}}</h2>
    <p>{{article.body}}</p>
    <p>{{article.date}}</p>
</div>
 {% endblock %}

articles/templates/articles/articles_list.html
 {% extends 'base_layout.html' %}
 {% block content %}
<h1>Article List</h1>
<div class ="articles">
    {% for article in articles %}
        <div class="article">
            <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>
            <p>{{article.snippet}}</p>
            <p>{{article.date}}</p>
        </div>
        {% endfor %}
</div>
{% endblock %}

articles/templates/articles/create.html
{% extends 'base_layout.html' %}

{% block content %}

<h1>Article creation space</h1>
<form class="site-form" action="{% url 'articles:create' %} " method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Create">
</form>
{% endblock %}

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
</head>
<body>
    <h1>About</h1>
    <p1>This is the about page</p1>
</body>
</html>

templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Articles</title>
    <link rel="stylesheet" href="{% static 'styles.css'%}">
</head>
<body>
<h1><a href="{% url 'articles:list' %}"><img src="{% static 'logo.png' %}" height = "100" width ="100"/></a></h1>
<nav>
    <ul>
        {% if user.is_authenticated %}

        <li>
            <form class="logout_link" action="{% url 'accounts:logout' %}">
                {% csrf_token %}
                <button type="submit">Logout</button>
            </form>
        </li>
        <li><a href="{% url 'articles:create' %}" class="highlight">Create New Article</a></li>
        {% else %}
            <li><a href="{% url 'accounts:login' %}">Login</a></li>
            <li><a href="{% url 'accounts:signup' %}">Signup</a></li>

        {% endif %}
    </ul>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homepage</title>
</head>
<body>
    <h1>Homepage</h1>
    <p1>Welcome to the homepage</p1>
</body>
</html>